"""add creator_id in group

Revision ID: 133f1afd01a6
Revises: cad8f549f48c
Create Date: 2025-08-30 23:46:00.359609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '133f1afd01a6'
down_revision: Union[str, Sequence[str], None] = 'cad8f549f48c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'groups', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'creator_id')
    # ### end Alembic commands ###
